name: Pre Pull Request
env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
on:
  pull_request:
    branches:
      - "master"
jobs:
  test_preview:
    strategy:
      matrix:
        version: [1.x.x]
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Setup Bunx
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{matrix.version}}
      - name: Install package use Bun
        run: |
          echo "We using bun to install package!"
          bun install

      - name: Check format
        run: |
          echo "Using pettier check"
          bun format
      - name: Add .env
        run: |
          echo "add DATABASE_URL"
          rm -rf .env
          touch .env
          echo "DATABASE_URL=${{env.DATABASE_URL}}" >> .env

      - name: Check database
        run: |
          echo "Using pettier check"
          bun db:check

      - name: Build bunx
        run: |
          echo "Bun is Building"
          bun build:server
